### ISSUE TITLE
Add examples for all values

### ISSUE THREAD

**Issue by cloveras** [vippsas/vipps-psp-api#31]
Orgno., MSN, etc: All values should have examples, to avoid the Swagger UI examples just showing "string".

Regex pattern too, to make local validation possible.

See the RFC: https://github.com/vippsas/vipps-rfc/blob/master/0001-api-guidelines.md

**Comment by rebeksburnett** [comment]
Done in: https://github.com/vippsas/vipps-psp-api/commit/dc3de723ce618b7d934fb367aad9e1561cf0e499
