### ISSUE TITLE
Signup: `name` vs `companyName`?

### ISSUE THREAD

**Issue by cloveras** [vippsas/vipps-psp-api#40]
There is both:

- `name`: https://github.com/vippsas/vipps-psp-api/blob/master/docs/signup/openapi.yaml#L224
- `companyName`: https://github.com/vippsas/vipps-psp-api/blob/master/docs/signup/openapi.yaml#L205

We should keep only `companyName`, right, @ananthb86?

**Comment by tht13** [comment]
`companyName` is the legal org name, `name` is our internal "saleUnitName", this allows multiple "brands" under one org, we have merchants that do this today already

**Comment by cloveras** [comment]
Ok, thanks. Will update the docs.
